kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '15'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"name":"beteps"},"name":"beteps-deployment","namespace":"beteps"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"beteps"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"prometheus.io/port":"8889","prometheus.io/scrape":"true"},"labels":{"app":"beteps","name":"beteps"}},"spec":{"containers":[{"args":["start"],"env":[{"name":"HOSTNAME","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"envFrom":[{"configMapRef":{"name":"beteps-config"}}],"image":"ghcr.io/bet01/beteps:v0.0.17","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/","port":4000}},"name":"beteps","ports":[{"containerPort":4000,"name":"http","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/","port":4000}},"resources":{},"securityContext":{"capabilities":{"drop":["ALL"]}},"volumeMounts":[]},{"args":["--config=/etc/otel-collector-config.yml"],"image":"otel/opentelemetry-collector-contrib-dev:latest","imagePullPolicy":"IfNotPresent","name":"otel","ports":[{"containerPort":55680},{"containerPort":55681}],"volumeMounts":[{"mountPath":"/etc/otel-collector-config.yml","name":"otel-config","subPath":"otel-collector-config.yml"}]}],"imagePullSecrets":[{"name":"gcr-json-key"},{"name":"ghcr-json-key"}],"securityContext":{},"serviceAccountName":"beteps","volumes":[{"configMap":{"name":"otel-config"},"name":"otel-config"}]}}}}
  name: beteps-deployment
  namespace: beteps
  labels:
    name: beteps
spec:
  replicas: 1
  selector:
    matchLabels:
      name: beteps
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: beteps
        name: beteps
      annotations:
        prometheus.io/port: '8889'
        prometheus.io/scrape: 'true'
    spec:
      restartPolicy: Always
      serviceAccountName: beteps
      imagePullSecrets:
        - name: gcr-json-key
        - name: ghcr-json-key
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /
              port: 4000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: beteps
          livenessProbe:
            httpGet:
              path: /
              port: 4000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          securityContext:
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: beteps-config
          image: 'ghcr.io/bet01/beteps:v0.0.17'
          args:
            - start
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: otel
          ports:
            - containerPort: 55680
              protocol: TCP
            - containerPort: 55681
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel-collector-config.yml
              subPath: otel-collector-config.yml
          terminationMessagePolicy: File
          image: 'otel/opentelemetry-collector-contrib-dev:latest'
          args:
            - '--config=/etc/otel-collector-config.yml'
      serviceAccount: beteps
      volumes:
        - name: otel-config
          configMap:
            name: otel-config
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
