kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
  name: beteps-config
  labels:
    app-name: beteps
data:
  COCKROACH_USERNAME: root
  PORT: '4000'
  COCKROACH_SSL: 'false'
  BETFRONT_TBII_URL: 'https://beteps.4781c9f1c6f17815.erlang-solutions.com'
  COCKROACH_DATABASE: betepsag
  COCKROACH_POOL: '10'
  COCKROACH_TABLE_NAME: events
  STORAGE_ADAPTER: cockroach
  COCKROACH_PORT: '26257'
  FILESYSTEM_DIR_PATH: /tmp/beteps
  CACHE_EXPIRATION: '3600000'
  KAFKA_HOSTS: 'redpanda.redpanda.svc.cluster.local:9092'
  RELEASE_COOKIE: cookie
  COCKROACH_HOSTNAME: syx-cockroachdb-public.cockroach-system.svc.cluster.local
