kind: Deployment
apiVersion: apps/v1
metadata:
  name: beteps-deployment
  labels:
    name: beteps
spec:
  replicas: 1
  selector:
    matchLabels:
      name: beteps
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: beteps
        name: beteps
      annotations:
        prometheus.io/port: '8889'
        prometheus.io/scrape: 'true'
    spec:
      restartPolicy: Always
      serviceAccountName: beteps
      imagePullSecrets:
        - name: gcr-json-key
        - name: ghcr-json-key
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /
              port: 4000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: beteps
          livenessProbe:
            httpGet:
              path: /
              port: 4000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          securityContext:
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: beteps-config
          image: 'ghcr.io/bet01/beteps:v0.0.17'
          args:
            - start
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: otel
          ports:
            - containerPort: 55680
              protocol: TCP
            - containerPort: 55681
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel-collector-config.yml
              subPath: otel-collector-config.yml
          terminationMessagePolicy: File
          image: 'otel/opentelemetry-collector-contrib-dev:latest'
          args:
            - '--config=/etc/otel-collector-config.yml'
      serviceAccount: beteps
      volumes:
        - name: otel-config
          configMap:
            name: otel-config
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
