kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: beteps-fileserver-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: thin
  volumeMode: Filesystem
