kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"otel-collector-config.yml":"receivers:\n 
      otlp:\n    protocols:\n      grpc:\n        endpoint:
      \"0.0.0.0:55680\"\n      http:\n        endpoint:
      \"0.0.0.0:55681\"\nprocessors:\n  batch:\n    send_batch_size: 1024\n   
      timeout: 5s\nexporters:\n  zipkin:\n    endpoint:
      \"http://zipkin.telemetry.svc.cluster.local:9411/api/v2/spans\"\nextensions:\n 
      zpages: {}\nservice:\n  extensions: [zpages]\n  pipelines:\n   
      traces:\n      receivers: [otlp]\n      processors: [batch]\n     
      exporters:
      [zipkin]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app-name":"beteps"},"name":"otel-config","namespace":"beteps"}}
  selfLink: /api/v1/namespaces/beteps/configmaps/otel-config
  resourceVersion: '10608446'
  name: otel-config
  uid: fa1cefa0-9058-4638-a7a4-619943e7250e
  creationTimestamp: '2021-06-02T14:12:55Z'
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2021-06-02T14:12:55Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:otel-collector-config.yml': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app-name': {}
  namespace: beteps
  labels:
    app-name: beteps
data:
  otel-collector-config.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:55680"
          http:
            endpoint: "0.0.0.0:55681"
    processors:
      batch:
        send_batch_size: 1024
        timeout: 5s
    exporters:
      zipkin:
        endpoint: "http://zipkin.telemetry.svc.cluster.local:9411/api/v2/spans"
    extensions:
      zpages: {}
    service:
      extensions: [zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [zipkin]
